name: user-address-manager
services:
  postgres:
    image: postgres:15
    container_name: user-address-manager-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - user-address-manager-db-data:/var/lib/postgresql/data
      - ./build/local/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

volumes:
  user-address-manager-db-data:
